module.exports = [
  { name: "Smartphone X", category: "Electronics", price: 699, description: "High-performance smartphone", stock: 50 },
  { name: "Laptop Pro", category: "Electronics", price: 1299, description: "Lightweight and powerful laptop", stock: 30 },
  { name: "Wireless Earbuds", category: "Electronics", price: 149, description: "Noise-cancelling earbuds", stock: 100 },
  { name: "4K TV", category: "Electronics", price: 899, description: "Ultra HD smart TV", stock: 25 },
  { name: "Gaming Console", category: "Electronics", price: 499, description: "Next-gen gaming console", stock: 40 },
  { name: "Digital Camera", category: "Electronics", price: 599, description: "High-resolution camera", stock: 20 },
  { name: "Bluetooth Speaker", category: "Electronics", price: 99, description: "Portable speaker with deep bass", stock: 70 },
  { name: "E-book Reader", category: "Electronics", price: 129, description: "Lightweight e-reader", stock: 50 },
  { name: "Smart Watch", category: "Electronics", price: 199, description: "Stylish and functional smartwatch", stock: 60 },
  { name: "Action Camera", category: "Electronics", price: 299, description: "Compact adventure camera", stock: 25 },
  { name: "Fiction Novel", category: "Books", price: 15, description: "Bestselling fiction book", stock: 200 },
  { name: "Science Textbook", category: "Books", price: 45, description: "Comprehensive science guide", stock: 80 },
  { name: "Cooking Recipes", category: "Books", price: 25, description: "Delicious recipes from around the world", stock: 100 },
  { name: "Business Strategies", category: "Books", price: 30, description: "Top strategies for success", stock: 90 },
  { name: "Kids' Storybook", category: "Books", price: 10, description: "Fun and educational stories", stock: 150 },
  { name: "Health & Wellness Guide", category: "Books", price: 20, description: "Tips for a healthier life", stock: 60 },
  { name: "Travel Diaries", category: "Books", price: 25, description: "Exploring the world through stories", stock: 75 },
  { name: "Programming Essentials", category: "Books", price: 50, description: "Guide to coding basics", stock: 40 },
  { name: "Hiking Backpack", category: "Textiles", price: 80, description: "Durable and spacious backpack", stock: 30 },
  { name: "Yoga Mat", category: "Textiles", price: 25, description: "Comfortable and non-slip mat", stock: 100 },
  { name: "Running Shoes", category: "Textiles", price: 120, description: "Lightweight and durable shoes", stock: 50 },
  { name: "Winter Jacket", category: "Textiles", price: 199, description: "Waterproof and insulated jacket", stock: 40 },
  { name: "Cotton T-shirt", category: "Textiles", price: 20, description: "Soft and breathable fabric", stock: 150 },
  { name: "Jeans", category: "Textiles", price: 60, description: "Stylish and comfortable fit", stock: 70 },
  { name: "Silk Scarf", category: "Textiles", price: 40, description: "Elegant and lightweight scarf", stock: 90 },
  { name: "Leather Belt", category: "Textiles", price: 35, description: "Premium leather craftsmanship", stock: 50 },
  { name: "Wool Sweater", category: "Textiles", price: 80, description: "Warm and cozy winter sweater", stock: 30 },
  { name: "Duvet Cover", category: "Textiles", price: 70, description: "Soft and durable bedding", stock: 25 },
  { name: "Office Chair", category: "Furniture", price: 150, description: "Ergonomic design for comfort", stock: 20 },
  { name: "Wooden Dining Table", category: "Furniture", price: 500, description: "Classic and sturdy table", stock: 15 },
  { name: "Bookshelf", category: "Furniture", price: 120, description: "Elegant and spacious storage", stock: 40 },
  { name: "Bed Frame", category: "Furniture", price: 300, description: "Modern and durable frame", stock: 10 },
  { name: "Coffee Table", category: "Furniture", price: 80, description: "Compact and stylish design", stock: 25 },
  { name: "Sofa Set", category: "Furniture", price: 1000, description: "Comfortable and luxurious set", stock: 8 },
  { name: "Desk Lamp", category: "Furniture", price: 40, description: "Bright and adjustable lighting", stock: 70 },
  { name: "Wall Art", category: "Decor", price: 60, description: "Beautiful and vibrant artwork", stock: 50 },
  { name: "Area Rug", category: "Decor", price: 120, description: "Soft and decorative rug", stock: 30 },
  { name: "Curtains", category: "Decor", price: 90, description: "Elegant and light-filtering curtains", stock: 40 },
  { name: "Cushion Cover", category: "Decor", price: 15, description: "Stylish and colorful designs", stock: 100 },
  { name: "Ceramic Vase", category: "Decor", price: 25, description: "Minimalist and modern vase", stock: 60 },
  { name: "Dining Set", category: "Kitchenware", price: 150, description: "Complete dinnerware set", stock: 20 },
  { name: "Cutlery Set", category: "Kitchenware", price: 50, description: "Premium stainless steel set", stock: 70 },
  { name: "Cooking Pan", category: "Kitchenware", price: 80, description: "Non-stick and durable pan", stock: 60 },
  { name: "Blender", category: "Kitchenware", price: 100, description: "Powerful and efficient blender", stock: 40 },
  { name: "Chef's Knife", category: "Kitchenware", price: 60, description: "Precision and sharpness for chefs", stock: 50 },
  { name: "Water Bottle", category: "Outdoor", price: 20, description: "Leak-proof and insulated bottle", stock: 150 },
  { name: "Camping Tent", category: "Outdoor", price: 200, description: "Durable and easy-to-setup tent", stock: 15 },
  { name: "Hiking Boots", category: "Outdoor", price: 150, description: "Comfortable and rugged boots", stock: 30 },
  { name: "Fitness Tracker", category: "Outdoor", price: 150, description: "Monitor your daily activity", stock: 50 },
  { name: "Smartphone A1", category: "Electronics", price: 699.99, description: "A sleek and powerful smartphone with a 6.5-inch display.", stock: 50 },
  { name: "Laptop B2", category: "Electronics", price: 1199.99, description: "A high-performance laptop for professionals.", stock: 30 },
  { name: "Wireless Earbuds C3", category: "Electronics", price: 129.99, description: "Compact and comfortable wireless earbuds.", stock: 100 },
  { name: "Tablet D4", category: "Electronics", price: 499.99, description: "Lightweight tablet with a 10-inch display.", stock: 40 },
  { name: "4K Smart TV E5", category: "Electronics", price: 899.99, description: "Stunning 4K Ultra HD Smart TV for your home entertainment.", stock: 20 },
  { name: "Gaming Console F6", category: "Electronics", price: 499.99, description: "Next-generation gaming console with powerful graphics.", stock: 25 },
  { name: "Bluetooth Speaker G7", category: "Electronics", price: 59.99, description: "Portable Bluetooth speaker with excellent sound quality.", stock: 75 },
  { name: "DSLR Camera H8", category: "Electronics", price: 799.99, description: "Capture high-quality photos with this advanced DSLR camera.", stock: 15 },
  { name: "Fitness Tracker I9", category: "Electronics", price: 99.99, description: "Track your daily activities with this fitness tracker.", stock: 200 },
  { name: "Mechanical Keyboard J10", category: "Electronics", price: 89.99, description: "Durable and responsive mechanical keyboard.", stock: 60 },
  { name: "Hardcover Novel K11", category: "Books", price: 24.99, description: "A thrilling mystery novel.", stock: 150 },
  { name: "Science Textbook L12", category: "Books", price: 89.99, description: "Comprehensive science textbook for college students.", stock: 100 },
  { name: "Cookbook M13", category: "Books", price: 34.99, description: "Delicious recipes from around the world.", stock: 120 },
  { name: "Self-Help Guide N14", category: "Books", price: 19.99, description: "Improve your life with these effective strategies.", stock: 180 },
  { name: "Children's Storybook O15", category: "Books", price: 14.99, description: "An enchanting storybook for kids.", stock: 250 },
  { name: "Fantasy Novel P16", category: "Books", price: 29.99, description: "Explore magical worlds in this epic fantasy novel.", stock: 90 },
  { name: "History Book Q17", category: "Books", price: 39.99, description: "Learn about world history in this detailed book.", stock: 80 },
  { name: "Digital Painting Kit R18", category: "Books", price: 49.99, description: "Master the art of digital painting with this kit.", stock: 70 },
  { name: "Photography Basics S19", category: "Books", price: 44.99, description: "Learn the fundamentals of photography.", stock: 65 },
  { name: "Coding Guide T20", category: "Books", price: 59.99, description: "Learn to code with this beginner's guide.", stock: 90 },
  { name: "Men's T-Shirt U21", category: "Apparel", price: 19.99, description: "Comfortable cotton T-shirt for men.", stock: 100 },
  { name: "Women's Jacket V22", category: "Apparel", price: 79.99, description: "Stylish jacket for women.", stock: 50 },
  { name: "Sports Shoes W23", category: "Apparel", price: 59.99, description: "Durable and lightweight sports shoes.", stock: 80 },
  { name: "Backpack X24", category: "Accessories", price: 49.99, description: "Spacious and durable backpack for daily use.", stock: 40 },
  { name: "Wristwatch Y25", category: "Accessories", price: 149.99, description: "Elegant wristwatch with a leather strap.", stock: 30 },
  { name: "Sunglasses Z26", category: "Accessories", price: 24.99, description: "Stylish sunglasses with UV protection.", stock: 100 },
  { name: "Leather Wallet A27", category: "Accessories", price: 39.99, description: "Premium leather wallet with multiple compartments.", stock: 120 },
  { name: "Noise-Canceling Headphones B28", category: "Electronics", price: 299.99, description: "High-quality headphones with active noise cancellation.", stock: 20 },
  { name: "Office Chair C29", category: "Furniture", price: 199.99, description: "Ergonomic office chair with adjustable features.", stock: 50 },
  { name: "Wooden Desk D30", category: "Furniture", price: 399.99, description: "Sturdy wooden desk for your home office.", stock: 30 },
  { name: "Memory Foam Pillow E31", category: "Home", price: 39.99, description: "Comfortable memory foam pillow for better sleep.", stock: 150 },
  { name: "Air Purifier F32", category: "Home", price: 299.99, description: "Improve indoor air quality with this air purifier.", stock: 25 },
  { name: "Coffee Maker G33", category: "Appliances", price: 79.99, description: "Brew delicious coffee at home.", stock: 40 },
  { name: "Blender H34", category: "Appliances", price: 49.99, description: "Compact and efficient blender for your kitchen.", stock: 60 },
  { name: "Microwave Oven I35", category: "Appliances", price: 129.99, description: "Versatile microwave oven with multiple settings.", stock: 30 },
  { name: "Electric Kettle J36", category: "Appliances", price: 34.99, description: "Quickly boil water with this electric kettle.", stock: 100 },
  { name: "Iron Box K37", category: "Appliances", price: 29.99, description: "Lightweight iron box for crisp clothes.", stock: 120 },
  { name: "Ceramic Plates L38", category: "Home", price: 24.99, description: "Set of ceramic plates for dining.", stock: 200 },
  { name: "Yoga Mat M39", category: "Fitness", price: 19.99, description: "Non-slip yoga mat for workouts.", stock: 80 },
  { name: "Dumbbell Set N40", category: "Fitness", price: 49.99, description: "Adjustable dumbbell set for strength training.", stock: 50 },
];
